unique_ids:
  assets:
    theme.css: 6G44GIEQQRJLILWU6GQSQO5BTDFT5ZI3
  forms:
    Form1: '1738456565683414971118883.9722'
  modules: {}
  scripts: {}
  server_modules:
    EmailAnalysis: GJD2GTJOV3X63YRTYTHCWTWDSBRVBZ44
    GetNewsletter: 23AO3MNR4YL2NQV4BCNQH5BL5IJ45J3F
    SendAnalysis: 2UKMEDSVNG23EOWTJ3OJKPWAYWGD62D6
    ServerModule: MLEBAKHWD25WEQZO47UBRW4W7NIZLKU3
